apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      containers:
      - name: ipapp
        image: ratanmd/ip-app:tag-version
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
    name: ip-app-nodport
spec: 
    type: NodePort
    selector:
        app: ip-app
    ports:
       - name: http
         port: 30002     
         targetPort: 8080
         nodePort: 30099
